# This example file shows how to configure a roomplan instance using the TOML format.
card_set = "fibonacci" # one of fibbonacci or t-shirt

# create a list of tickets you want to estimate for this session
[[tickets]]
name = "Ticket 1"
description = "This is the first ticket."

[[tickets]]
name = "Ticket 2"
description = "This is the second ticket."
