name: "Chromatic"

on:
  push:
    paths:
      - "frontend/**"
      - "!**/*.md"
  pull_request:
    branches:
      - master
    paths:
      - "frontend/**"
      - "!**/*.md"
    types: [opened, synchronize, reopened]

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
        working-directory: frontend
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          workingDir: frontend
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: "master"
          skip: "dependabot/**"
