name: Frontend Lint
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - "frontend/**"
    types: [opened, synchronize, reopened]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Cache dependencies
        id: cache-node-modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-build-${{env.cache-name}}-${{ hashFiles('frontend/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{env.cache-name}}-${{ hashFiles('frontend/bun.lock') }}
      - if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: bun install
        working-directory: frontend
      - name: Run lint
        run: bun lint
        working-directory: frontend
